#!/bin/bash

rm -rf output
mkdir output

# assemble
rasm hello -o output/disc -s -ss -sb -oi output/disc.sna

# loader
awk 'sub("$", "\r")' loader.bas > output/disc.bas

# disk image
idsk output/disk.dsk -n
idsk output/disk.dsk -i output/disc.bas -t 0
idsk output/disk.dsk -i output/disc.bin -t 1 -e 8000

